AWSTemplateFormatVersion: '2010-09-09'
Description: 'Minimal S3 bucket'

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket

Outputs:
  BucketName:
    Value: !Ref S3Bucket
    Description: 'S3 bucket name'